### ISSUE TITLE
Video 5, PromptContainer

### ISSUE THREAD

**Issue by Luburic** [ReactjsProgram/React-Fundamentals#3]
This isn't a breaking issue, but in [PromptContainer.js](https://github.com/ReactjsProgram/React-Fundamentals/blob/video5/app/containers/PromptContainer.js), on line 26 you wrote `this.state.username`, but shouldn't that field contain an empty string based on line 17?

Since it works I'm guessing that setState is asynchronous (possibly utilizing ES6 jobs or something). However, if that is the case, what was the point of caching the username in a variable?

**Comment by yanisurbis** [comment]
@Luburic I think you are not completely understand JS. Plese consider this example:

``` js
let field1 = 2
let obj = { field1 }
let ref = obj.field1
console.log(` ${obj.field1} ${ref}`)
// 2 2
obj.field1 = 4
console.log(` ${obj.field1} ${ref}`)
// 4 2
```

# 

> what was the point of caching the username in a variable?

I don't understand as well :+1:

**Comment by Luburic** [comment]
@yanisurbis What I don't understand is how your example correlates to what I said in my first post?

**Comment by tylermcginnis** [comment]
@Luburic You're exactly right. setState is async. In the video I made a mistake by using this.state.username rather than the username variable I created. But since setState is async, both work. Going to close this as re-doing the whole video for that mistake would take too much time at the moment. Let me know if you have any other questions.
